#!/bin/bash
set -e

rm -rf $TLSCACERTIFICATEPATH
mkdir -p $TLSCACERTIFICATEPATH

#PASSIVEPORTS="1026 1030"

echo "creating ssl certificates"
echo "$TLSRSACERTIFICATEFILE" > $TLSCACERTIFICATEPATH/server.crt
echo "$TLSCACERTIFICATEKEYFILE" > $TLSCACERTIFICATEPATH/server.key

chmod 400 $TLSCACERTIFICATEPATH/*

chown -R root.root $TLSCACERTIFICATEPATH
